### PR TITLE
SOC, const, plots, and FP tests update

### PR DESCRIPTION
**Pull request by treycole**
Changed all tests to have atomic spacings in units of meters instead of angstroms. Changed hbar to units of Joules in [constants](https://github.com/tbcole/Majoranas-in-Synthetic-Atoms/tree/master/Modules/constants.py) then converted to eV in the [plotting function](https://github.com/tbcole/Majoranas-in-Synthetic-Atoms/tree/master/Modules/operators.py). When using hbar in units of eV the energy eigenvalues are not consistent with using Joules then converting to eV, because hbar is being squared.

### CODE REVIEW

**Comment by BenjaminWoods1** [comment]
I would advice not to use Joules and meters, but something like eV or meV and nm or angstroms. You may run into floating point errors using Joules and meters since the numbers will be so small

**Comment by treycole** [comment]
If I use nm and units of eV for hbar then will this still give the correct energies?

**Comment by BenjaminWoods1** [comment]
It should work with any units you choose to work with.

**Comment by BenjaminWoods1** [comment]
Just be aware that hbar^2/2m has units of eV nm^2, not just eV

**Comment by treycole** [comment]
if `1 [eV] = 1.6e-19 [J]` and Joules has units of `[m]` in it then why does hbar expressed in units of [ev] result in having `hbar^2 ~ [nm^2]` instead of `[m^2]`? How does using nm cancel units correctly? Wouldn't you need to use meters?

**Comment by BenjaminWoods1** [comment]
You can get it in eV m^2, but then convert it to eV nm^2 by multiplying by (10^9)^2=10^18

**Comment by treycole** [comment]
My confusion is due to the fact that when using eV and m I get energy values on the order of 1e19. I guess this could be correct since the size of the square well is very small and E~L^-2. 
image

**Comment by treycole** [comment]
I just defined a new constant where I used all units of Joules and meters then multiplied by 10^20 and multiplied by electron charge to get hbar^2/m0 ~ [eV A^2]. That way there is no confusion about the numerics contained within using hbar in the value given in units of [eV*s], since there is a conversion factor being squared. So now the inputs are in Angstroms and the free particle looks like this 
image
The SOC with alpha = 0.2 and gamma = 0 and no potential looks like this
image
Should there be a gap be opening at the edge of the Brillouin zone?

**Comment by BenjaminWoods1** [comment]
There shouldn’t be gaps opening with spin orbit coupling. Did you check what the Hamiltonian looks like for a 3x3 lattice. That should show where the mistake is

**Pull request merged**
